ansibleenv:
  zone_compartment_id: <path:ocivault#zone_compartment_id#latest | base64decode>
  domain: <path:ocivault#openg2p_domain#latest | base64decode>
  hostnames:
    - api-internal.<path:ocivault#openg2p_domain#latest | base64decode>
    - iam.<path:ocivault#openg2p_domain#latest | base64decode>
domain_ssl_secret_name: <path:ocivault#openg2p_domain_ssl_secret_name#latest | base64decode>


gateway: 
  defaults:
    env: 
      ISTIO_META_IDLE_TIMEOUT: 300s
    label:
        istio: ingressgateway-internal    
    service:
      type: LoadBalancer
      ports:
      - port: 15021
        targetPort: 15021
        name: status-port
        protocol: TCP
      - port: 80
        targetPort: 8080
        name: http2
        protocol: TCP
      - port: 443
        targetPort: 8080
        name: https
        protocol: TCP
      - port: 61616
        targetPort: 61616
        name: activemq
        protocol: TCP
      - port: 5432
        targetPort: 5432
        name: postgres
        protocol: TCP
      annotations: 
        oci.oraclecloud.com/load-balancer-type: "lb"
        service.beta.kubernetes.io/oci-load-balancer-internal: "true"
        service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
        service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
        service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
        service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"    
        service.beta.kubernetes.io/oci-load-balancer-tls-secret: <path:ocivault#openg2p_domain_ssl_secret_name#latest | base64decode>
        oci.oraclecloud.com/oci-network-security-groups: <path:ocivault#mosip_public_lb_nsg_id#latest | base64decode>
        oci-network-load-balancer.oraclecloud.com/subnet: <path:ocivault#mosip_public_lb_subnet_id#latest | base64decode>
        oci.oraclecloud.com/security-rule-management-mode: "None"  
        external-dns.alpha.kubernetes.io/hostname: api-internal.<path:ocivault#openg2p_domain#latest | base64decode> , iam.<path:ocivault#openg2p_domain#latest | base64decode> ,activemq.<path:ocivault#openg2p_domain#latest | base64decode>, kibana.<path:ocivault#openg2p_domain#latest | base64decode>, regclient.<path:ocivault#openg2p_domain#latest | base64decode>, admin.<path:ocivault#openg2p_domain#latest | base64decode> , minio.<path:ocivault#openg2p_domain#latest | base64decode> , kafka.<path:ocivault#openg2p_domain#latest | base64decode>, postgres.<path:ocivault#openg2p_domain#latest | base64decode>, smtp.<path:ocivault#openg2p_domain#latest | base64decode>, landingpage.<path:ocivault#openg2p_domain#latest | base64decode> 
      loadBalancerIP: "10.0.1.230"