postgres-init:
  backoffLimit: 6
jobAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  dbUserPasswords:
    dbuserPassword: ""

  databases:
    mosip_master:
      enabled: false
      branch: develop

    mosip_audit:
      enabled: true
      repoUrl: https://github.com/oci-sunbird/audit-manager.git
      branch: v1.2.0.1

    mosip_keymgr:
      enabled: true 
      repoUrl: https://github.com/oci-sunbird/keymanager.git
      branch: v1.2.0.1-B3

    mosip_kernel:
      enabled: false
      branch: develop

    mosip_idmap:
      enabled: false
      branch: develop

    mosip_prereg:
      enabled: false
      branch: develop

    mosip_idrepo:
      enabled: false
      branch: develop

    mosip_ida:
      enabled: false
      branch: develop

    mosip_credential:
      enabled: false
      branch: develop

    mosip_regprc:
      enabled: false
      branch: develop

    mosip_regdevice:
      enabled: false
      branch: develop

    mosip_authdevice:
      enabled: false
      branch: develop

    mosip_pms:
      enabled: false
      branch: develop

    mosip_hotlist:
      enabled: false
      branch: develop

    mosip_resident:
      enabled: false
      branch: develop

    mosip_toolkit:
      enabled: false
      branch: develop

    mosip_digitalcard:
      enabled: false
      branch: develop

    mosip_esignet:
      enabled: true
      repoUrl: https://github.com/oci-sunbird/esignet.git
      branch: v1.2.0

    mosip_mockidentitysystem:
      enabled: true
      repoUrl: https://github.com/oci-sunbird/esignet-mock-services.git
      branch: v0.9.1

