keycloak_istio_enabled: true
keycloakExternalHost: iam.<path:ocivault#mosip_domain#latest | base64decode> 
keycloak_db_password: <path:ocivault#mosip_pg_password#latest | base64decode> 
domain_ssl_secret_name: <path:ocivault#openg2p_domain_ssl_secret_name#latest | base64decode>

keycloak-init: 
  backoffLimit: 10
  # jobAnnotations:
  #   argocd.argoproj.io/sync-wave: "-95"
  frontend: https://iam.<path:ocivault#mosip_domain#latest | base64decode>/auth
  clientSecrets:
    - name: mosip_abis_client_secret
      secret: "<path:ocivault#mosip_abis_client_secret#latest | base64decode>"
    - name: mosip_admin_client_secret
      secret: "<path:ocivault#mosip_admin_client_secret#latest | base64decode>"
    - name: mosip_admin_services_client_secret
      secret: "<path:ocivault#mosip_admin_services_client_secret#latest | base64decode>"
    - name: mosip_auth_client_secret
      secret: "<path:ocivault#mosip_auth_client_secret#latest | base64decode>"
    - name: mosip_crereq_client_secret
      secret: "<path:ocivault#mosip_crereq_client_secret#latest | base64decode>"
    - name: mosip_creser_client_secret
      secret: "<path:ocivault#mosip_creser_client_secret#latest | base64decode>"
    - name: mosip_datsha_client_secret
      secret: "<path:ocivault#mosip_datsha_client_secret#latest | base64decode>"
    - name: mosip_ida_client_secret
      secret: "<path:ocivault#mosip_ida_client_secret#latest | base64decode>"
    - name: mosip_misp_client_secret
      secret: "<path:ocivault#mosip_misp_client_secret#latest | base64decode>"
    - name: mosip_partner_client_secret
      secret: "<path:ocivault#mosip_partner_client_secret#latest | base64decode>"
    - name: mosip_partnermanager_client_secret
      secret: "<path:ocivault#mosip_partnermanager_client_secret#latest | base64decode>"
    - name: mosip_pms_client_secret
      secret: "<path:ocivault#mosip_pms_client_secret#latest | base64decode>"
    - name: mosip_policymanager_client_secret
      secret: "<path:ocivault#mosip_policymanager_client_secret#latest | base64decode>"
    - name: mosip_reg_client_secret
      secret: "<path:ocivault#mosip_reg_client_secret#latest | base64decode>"
    - name: mosip_regproc_client_secret
      secret: "<path:ocivault#mosip_regproc_client_secret#latest | base64decode>"
    - name: mosip_resident_client_secret
      secret: "<path:ocivault#mosip_resident_client_secret#latest | base64decode>"
    - name: mosip_prereg_client_secret
      secret: "<path:ocivault#mosip_prereg_client_secret#latest | base64decode>"
    - name: mosip_creser_idpass_client_secret
      secret: "<path:ocivault#mosip_creser_idpass_client_secret#latest | base64decode>"
    - name: mosip_syncdata_client_secret
      secret: "<path:ocivault#mosip_syncdata_client_secret#latest | base64decode>"
    - name: mosip_deployment_client_secret
      secret: "<path:ocivault#mosip_deployment_client_secret#latest | base64decode>"
    - name: mpartner_default_auth_secret
      secret: "<path:ocivault#mpartner_default_auth_secret#latest | base64decode>"
    - name: mosip_idrepo_client_secret
      secret: "<path:ocivault#mosip_idrepo_client_secret#latest | base64decode>"
    - name: mpartner_default_print_secret
      secret: "<path:ocivault#mpartner_default_print_secret#latest | base64decode>"
    - name: mosip_hotlist_client_secret
      secret: "<path:ocivault#mosip_hotlist_client_secret#latest | base64decode>"
    - name: mpartner_default_mobile_secret
      secret: "<path:ocivault#mpartner_default_mobile_secret#latest | base64decode>"
    - name: mpartner_default_digitalcard_secret
      secret: "<path:ocivault#mpartner_default_digitalcard_secret#latest | base64decode>"
    - name: mosip_digitalcard_client_secret
      secret: "<path:ocivault#mosip_digitalcard_client_secret#latest | base64decode>"
    - name: mosip_testrig_client_secret
      secret: "<path:ocivault#mosip_testrig_client_secret#latest | base64decode>"



keycloak:
  # commonAnnotations:
  #   argocd.argoproj.io/sync-wave: "-95"
  image: 
    repository: mosipqa/mosip-keycloak
    tag: 1.2.0.1

  service:
    type: ClusterIP

  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.profile.feature.upload_scripts=enabled"
      #value: "-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.import=/config/realm-mosip.json"

  proxyAddressForwarding: true

  replicaCount: 1

  # Enable if replicaCount > 1
  serviceDiscovery:
    enabled: true

  resources:
    limits: {}
    #   cpu: 250m
    #   memory: 1Gi
    requests:
      cpu: 200m
      memory: 1000Mi

  rbac:
    create: true
    rules:
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - get
      - list

    
  initContainers:
    - name: postgres-checker
      image: jbergknoff/postgresql-client
      command:
        - 'sh'
        - '-c'
        - 'until pg_isready -U ${KEYCLOAK_DB_USERNAME} -h ${KEYCLOAK_DB_HOSTNAME} -p ${KEYCLOAK_DB_PORT:-5432} -d ${KEYCLOAK_DB_DBNAME:-bitnami_keycloak}; do sleep 3; done'
      env: 
        - name: KEYCLOAK_DB_HOSTNAME
          value: "postgres-postgresql.postgres"
        - name: KEYCLOAK_DB_USERNAME
          value: "bn_keycloak"
        - name: KEYCLOAK_DB_DBNAME
          value: "bitnami_keycloak"
  
  auth:
    adminUser: admin
    adminPassword: <path:ocivault#mosip_keycloak_admin_password#latest | base64decode>
  
  ingress:
    enabled: false
 
  postgresql:
    enabled: false
  
  externalDatabase:
    host: postgres-postgresql.postgres
    database: bitnami_keycloak
    user: bn_keycloak
    existingSecret: postgres-postgresql
    existingSecretPasswordKey: password
  