dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_master:
    enabled: false
    branch: develop

  mosip_audit:
    enabled: true
    repoUrl: {{ .Values.postgres.mosip_audit_manager_repo }}
    branch: {{ .Values.postgres.mosip_audit_manager_rel_version }}

  mosip_keymgr:
    enabled: true 
    repoUrl: {{ .Values.postgres.mosip_keymanager_repo }}
    branch: {{ .Values.postgres.mosip_keymanager_rel_version }}

  mosip_kernel:
    enabled: false
    branch: develop

  mosip_idmap:
    enabled: false
    branch: develop

  mosip_prereg:
    enabled: false
    branch: develop

  mosip_idrepo:
    enabled: false
    branch: develop

  mosip_ida:
    enabled: false
    branch: develop

  mosip_credential:
    enabled: false
    branch: develop

  mosip_regprc:
    enabled: false
    branch: develop

  mosip_regdevice:
    enabled: false
    branch: develop
   
  mosip_authdevice:
    enabled: false
    branch: develop

  mosip_pms:
    enabled: false
    branch: develop

  mosip_hotlist:
    enabled: false
    branch: develop

  mosip_resident:
    enabled: false
    branch: develop

  mosip_toolkit:
    enabled: false
    branch: develop

  mosip_digitalcard:
    enabled: false
    branch: develop

  mosip_esignet:
    enabled: true
    repoUrl: {{ .Values.postgres.mosip_esignet_repo }}
    branch: {{ .Values.postgres.mosip_esignet_rel_version }}

  mosip_mockidentitysystem:
    enabled: true
    repoUrl: {{ .Values.postgres.mosip_mockidentitysystem_repo }}
    branch: {{ .Values.postgres.mosip_mockidentitysystem_rel_version }}
