---
- name: Update DNS zone records
  hosts: bastion
  environment:
    OCI_ANSIBLE_AUTH_TYPE: "instance_principal"
  tasks:
    - name: Checking if zone is already present
      oracle.oci.oci_dns_zone_facts:
        compartment_id: "{{zone_compartment_id}}"
        name: "{{domain}}"
      register: result
  
    - name: Create zone 
      oracle.oci.oci_dns_zone:
        name: "{{domain}}"
        compartment_id: "{{zone_compartment_id}}"
        zone_type: PRIMARY
      when: result.zones | length == 0

    - name: Get the external ip of the ingress controller
      shell: |
        EXTERNAL_IP=$(kubectl get svc -n istio-system istio-gateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo $EXTERNAL_IP
      register: istio_gw_external_ip

    - name: Get the internal ip of the nginx ingress controller
      shell: |
        INTERNAL_IP=$(kubectl get svc -n istio-system istio-gateway -o jsonpath='{.status.loadBalancer.ingress[1].ip}')
        echo $INTERNAL_IP
      register: istio_gw_internal_ip

    - name: Update public rrset
      oracle.oci.oci_dns_rrset:
        zone_name_or_id: "{{domain}}"
        domain: "{{item}}.{{domain}}"
        rtype: "A"
        update_items:
        - domain: "{{item}}.{{domain}}"
          rdata: "{{istio_gw_external_ip.stdout}}"
          rtype: "A"
          ttl: 300
        compartment_id: "{{zone_compartment_id}}"
      with_items:
        - api
        - prereg
        - resident
        - esignet
        - spar
        - grafana
        - keycloak
        - opensearch
        - postgres

    - name: Update private rrset
      oracle.oci.oci_dns_rrset:
        zone_name_or_id: "{{domain}}"
        domain: "{{item}}.{{domain}}"
        rtype: "A"
        update_items:
        - domain: "{{item}}.{{domain}}"
          rdata: "{{istio_gw_internal_ip.stdout}}"
          rtype: "A"
          ttl: 300
        compartment_id: "{{zone_compartment_id}}"
      with_items:
        - api-internal
        - activemq
        - kibana
        - regclient
        - admin
        - minio
        - kafka
        - pmp
        - smtp
        - signup
        - compliance
        - odk
        - keymanager