postgres:
  db_password: <path:ocivault#openg2p_pg_password#latest | base64decode> 

domain: <path:ocivault#openg2p_domain#latest | base64decode> 

spar-self-service-ui:
  global:
    hostname: "spar.<path:ocivault#openg2p_domain#latest | base64decode>"
  envVars:
    SPAR_CORE_DB_HOSTNAME: "postgres-postgresql.postgres"
    SPAR_CORE_DEFAULT_ID_TOKEN_VERIFY_AT_HASH: "false"
    # Replace the following URLs with available e-Signet issuer url and JWKS url.
    SPAR_CORE_AUTH_DEFAULT_ISSUERS: '["https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>/v1/esignet"]'
    SPAR_CORE_AUTH_DEFAULT_JWKS_URLS: '["https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>/v1/esignet/oauth/.well-known/jwks.json"]'
    # Uncomment the following if using Sunbird Mapper Registry.
    # SPAR_CONNECTOR_G2PCONNECT_MAPPER_RESOLVE_URL: "http://mapper/v0.1.0/mapper/resolve"
    # SPAR_CONNECTOR_G2PCONNECT_MAPPER_LINK_URL: "http://mapper/v0.1.0/mapper/link"
    # SPAR_CONNECTOR_G2PCONNECT_MAPPER_UPDATE_URL: "http://mapper/v0.1.0/mapper/update"

  envVarsFrom:
    # Comment out this section, if you donot have PostgreSQL installed already.
    SPAR_CORE_DB_PASSWORD:
      secretKeyRef:
        name: postgres-postgresql
        key: password

  # Enable this if you donot have PostgreSQL installed already.
  postgresql:
    enabled: false

  # Enable only one of the following mappers.
  # Defaults is SPAR Mapper
  spar-g2pconnect-id-mapper:
    enabled: true
    # Comment out this section, if you donot have PostgreSQL installed already.
    envVars:
      SPAR_G2PCONNECT_MAPPER_DB_HOSTNAME: "postgres-postgresql.postgres"
    # Comment out this section, if you donot have PostgreSQL installed already.
    envVarsFrom:
      SPAR_G2PCONNECT_MAPPER_DB_PASSWORD:
        secretKeyRef:
          name: "postgres-postgresql"
          key: password

  sunbird-rc-g2p-mapper-registry:
    enabled: false
    # Comment out the following, if you donot have PostgreSQL installed already.
    registry:
      envVars:
        connectionInfo_uri: "jdbc:postgresql://postgres-postgresql.postgres:5432/spardb"
      envVarsFrom:
        connectionInfo_password:
          secretKeyRef:
            name: postgres-postgresql
            key: password

  # Uncomment the following if you donot have istio installed already.
  # istio:
  #   enabled: false
  # ingress:
  #   enabled: true
  # mapper:
  #   istio:
  #     enabled: false
  #   ingress:
  #     enabled: true

  # For more values checkout the full helm chart at
  # https://github.com/OpenG2P/openg2p-helm/blob/main/charts/social-payments-account-registry/values.yaml



social-payments-account-registry:
  global:
    hostname: "spar.<path:ocivault#openg2p_domain#latest | base64decode>"
  envVars:
    SPAR_CORE_DB_HOSTNAME: "postgres-postgresql.postgres"
    SPAR_CORE_DEFAULT_ID_TOKEN_VERIFY_AT_HASH: "false"
    # Replace the following URLs with available e-Signet issuer url and JWKS url.
    SPAR_CORE_AUTH_DEFAULT_ISSUERS: '["https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>/v1/esignet"]'
    SPAR_CORE_AUTH_DEFAULT_JWKS_URLS: '["https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>/v1/esignet/oauth/.well-known/jwks.json"]'
    # Uncomment the following if using Sunbird Mapper Registry.
    # SPAR_CONNECTOR_G2PCONNECT_MAPPER_RESOLVE_URL: "http://mapper/v0.1.0/mapper/resolve"
    # SPAR_CONNECTOR_G2PCONNECT_MAPPER_LINK_URL: "http://mapper/v0.1.0/mapper/link"
    # SPAR_CONNECTOR_G2PCONNECT_MAPPER_UPDATE_URL: "http://mapper/v0.1.0/mapper/update"

  envVarsFrom:
    # Comment out this section, if you donot have PostgreSQL installed already.
    SPAR_CORE_DB_PASSWORD:
      secretKeyRef:
        name: postgres-postgresql
        key: password

  # Enable this if you donot have PostgreSQL installed already.
  postgresql:
    enabled: false

  # Enable only one of the following mappers.
  # Defaults is SPAR Mapper
  spar-g2pconnect-id-mapper:
    enabled: true
    # Comment out this section, if you donot have PostgreSQL installed already.
    envVars:
      SPAR_G2PCONNECT_MAPPER_DB_HOSTNAME: "postgres-postgresql.postgres"
    # Comment out this section, if you donot have PostgreSQL installed already.
    envVarsFrom:
      SPAR_G2PCONNECT_MAPPER_DB_PASSWORD:
        secretKeyRef:
          name: "postgres-postgresql"
          key: password

  sunbird-rc-g2p-mapper-registry:
    enabled: false
    # Comment out the following, if you donot have PostgreSQL installed already.
    registry:
      envVars:
        connectionInfo_uri: "jdbc:postgresql://postgres-postgresql.postgres:5432/spardb"
      envVarsFrom:
        connectionInfo_password:
          secretKeyRef:
            name: postgres-postgresql
            key: password

  # Uncomment the following if you donot have istio installed already.
  # istio:
  #   enabled: false
  # ingress:
  #   enabled: true
  # mapper:
  #   istio:
  #     enabled: false
  #   ingress:
  #     enabled: true

  # For more values checkout the full helm chart at
  # https://github.com/OpenG2P/openg2p-helm/blob/main/charts/social-payments-account-registry/values.yaml
